<?php
/**
 * Netstarter Pty Ltd.
 *
 * @category    CameraHouse_Contact
 * @package     CameraHouse_Contact
 * @author      Netstarter Team <contact@netstarter.com>
 * @copyright   Copyright (c) 2016 Netstarter Pty Ltd. (http://www.netstarter.com.au)
 */
// @codingStandardsIgnoreFile
/**
 * Contact Us template - sidebar
 *
 * @var $block \CameraHouse\Contact\Block\ContactForm
 */
?>
<div class="faq-link-wrapper">
    <div class="faq-link-set">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact_us_left_content')->toHtml();?>
    </div>
</div>
